export const church = {
  name: "원당교회",
  nameEn: "Wondang Church",
  denomination: "대한예수교장로회",
  pastor: "양승철",
  pastorTitle: "담임목사",
  slogan: "제자 되고 제자 삼는 원당교회",
  subSlogan: "예배로 하나님께, 사랑으로 이웃에게 나아가는 원당교회입니다.",
  address: "인천광역시 검단구 이음1로 320 원당교회",
  addressShort: "인천광역시 검단구 이음1로 320",
  tel: "032-563-4943",
  fax: "032-563-1425",
  email: "wdchurch@wdchurch.com",
  map: {
    lat: 37.5890672,
    lng: 126.7192687,
  },
  nav: [
    {
      title: "교회소개",
      href: "/about",
      children: [
        { title: "인사말", href: "/about#greeting" },
        { title: "섬기는 분들", href: "/about#staff" },
        { title: "교회발자취", href: "/about#history" },
        { title: "비전·사명", href: "/about#vision" },
        { title: "선교", href: "/about#mission" },
        { title: "오시는 길", href: "/about#location" },
        { title: "3D 공간 안내", href: "/campus" },
      ],
    },
    {
      title: "말씀과 찬양",
      href: "/sermons",
      children: [
        { title: "주일예배", href: "/sermons?category=주일예배" },
        { title: "금요예배", href: "/sermons?category=금요예배" },
        { title: "새벽예배", href: "/sermons?category=새벽예배" },
        { title: "쉐키나찬양단 (1·2·3부 통합)", href: "/sermons?category=쉐키나찬양단" },
        { title: "할렐루야찬양대", href: "/sermons?category=할렐루야찬양대" },
      ],
    },
    {
      title: "제자훈련",
      href: "/discipleship",
      children: [
        { title: "새가족반", href: "/discipleship#courses" },
        { title: "양육반", href: "/discipleship#courses" },
        { title: "제자반", href: "/discipleship#courses" },
        { title: "사역반", href: "/discipleship#courses" },
        { title: "수료자 명단", href: "/discipleship#graduates" },
      ],
    },
    {
      title: "다음세대",
      href: "/next-generation",
      children: [
        { title: "유아부", href: "/next-generation#toddler" },
        { title: "유치부", href: "/next-generation#kindergarten" },
        { title: "유년부", href: "/next-generation#lower-elementary" },
        { title: "초등부", href: "/next-generation#elementary" },
        { title: "중등부", href: "/next-generation#middle" },
        { title: "고등부", href: "/next-generation#high" },
        { title: "청년부", href: "/next-generation#young-adult" },
        { title: "영어예배부", href: "/next-generation#english" },
        { title: "어와나(AWANA)", href: "/next-generation#awana" },
      ],
    },
    {
      title: "커뮤니티",
      href: "/community",
      children: [
        { title: "공지사항", href: "/community?category=공지사항" },
        { title: "교회소식", href: "/community?category=교회소식" },
        { title: "주보", href: "/community?category=주보" },
        { title: "새가족소개", href: "/community?category=새가족소개" },
        { title: "가정예배순서지", href: "/community?category=가정예배순서지" },
        { title: "봉사 섬김이", href: "/community?category=봉사%20섬김이" },
        { title: "갤러리", href: "/gallery" },
      ],
    },
    {
      title: "스마트 헌금",
      href: "/offering",
      children: [
        { title: "일반 헌금", href: "https://aq.gy/f/Smhf4" },
        { title: "건축헌금", href: "https://aq.gy/f/gL9jy" },
        { title: "식권", href: "https://aq.gy/f/B6Tx1" },
      ],
    },
  ],
} as const

export type NavItem = (typeof church.nav)[number]

export const worshipPlaces = {
  mainSanctuary: "믿음관(FAITH) 1층 비전홀 (예배당)",
  kindergarten: "사랑관(LOVE) 2층 유치부",
} as const

// Education departments, shared by the 다음세대 page and the home 교회학교 strip.
export const departments = [
  {
    id: "toddler",
    name: "유아부",
    age: "2~4세(12개월 이상)와 부모",
    time: "주일 오전 10:10~10:50",
    place: "소망관 1층 사무엘홀",
    desc: "부모님과 함께 찬양하고 예배하며, 하나님과 말씀을 중심으로 예수님의 작은 제자로 자라가는 공동체입니다.",
    image: "/images/next-generation/toddler.jpg",
  },
  {
    id: "kindergarten",
    name: "유치부",
    age: "5~7세",
    time: "주일 오전 11:00",
    place: worshipPlaces.kindergarten,
    desc: "즐겁게 찬양하고 기도하며 말씀을 배우고, 바른 예배 습관과 말씀 묵상으로 세상의 빛과 소금이 되는 예수님의 꼬마 제자를 세웁니다.",
    image: "/images/next-generation/kindergarten.jpg",
  },
  {
    id: "lower-elementary",
    name: "유년부",
    age: "초등학교 1~3학년",
    time: "주일 오후 12:00~1:20",
    place: "소망관 1층",
    desc: "믿음의 눈으로 세상을 바라보며 순종하는 예수님의 제자, 유년부! 하나님께서 맡기신 이 세상 가운데서도 믿음의 눈으로 세상을 바라보고, 하나님의 말씀에 순종하며 나아갑니다.",
    image: "/images/next-generation/유년부.jpg",
  },
  {
    id: "elementary",
    name: "초등부",
    age: "초등학교 4~6학년",
    time: "주일 오전 10:55~12:20",
    place: "사랑관 2층 드림홀",
    desc: "즐겁게 찬양하고 기도로 깊어지며 말씀과 성경적 세계관으로 성장하는, 제자 되고 제자 삼는 공동체입니다.",
    image: "/images/next-generation/elementary.png",
  },
  {
    id: "middle",
    name: "중등부",
    age: "중학교 1~3학년(14~16세)",
    time: "주일 오전 11:00~12:20",
    place: "사랑관 3층 디모데홀",
    desc: "바른 말씀으로 건강한 자아와 하나님의 가치관을 세우고, 세상이 감당하지 못하는 믿음의 사람으로 훈련받습니다.",
    image: "/images/next-generation/중등부.jpeg",
    contain: true,
  },
  {
    id: "high",
    name: "고등부",
    age: "고등학교 1~3학년(17~19세)",
    time: "주일 오전 11:00~12:20",
    place: "소망관 2층 다니엘홀",
    desc: "말씀과 기도로 건강한 자기 이해와 하나님의 가치관을 세워, 하나님을 기쁘시게 하는 믿음의 사람으로 성장합니다.",
    image: "/images/next-generation/high.jpg",
  },
  {
    id: "young-adult",
    name: "청년부",
    age: "20~35세",
    time: "주일 오후 2:00~3:30",
    place: "사랑관 3층 디모데홀",
    desc: "한 성령 안에서 예배하며 예수 생명으로 회복되고, 믿음과 사랑으로 서로를 세워 세상을 변화시키는 예수님의 제자 공동체입니다.",
    image: "/images/next-generation/young-adult.jpg",
  },
  {
    id: "english",
    name: "영어예배부",
    age: "초등학교 1~6학년",
    time: "주일 오전 9:00~10:10",
    place: "사랑관 2층 드림홀",
    desc: "영어 학습보다 예배의 본질에 집중하며, 영어 찬양과 말씀을 도구로 하나님께 즐겁게 나아가고 하나님을 경험하도록 돕습니다.",
    image: "/images/next-generation/english.jpg",
    contain: true,
  },
  {
    id: "awana",
    name: "어와나(AWANA)",
    age: "7세~고등학생",
    time: "주일 오후 2:00 · YM 토요일 오전 10:00",
    place: "사랑관 2층 드림홀 · 1층 만나홀",
    desc: "복음과 성경 암송, 재미있는 활동을 통해 어린이와 청소년이 예수 그리스도를 알고 사랑하고 섬기도록 훈련합니다. 참여 전 입단 과정이 필요합니다.",
    image: "/images/next-generation/어와나1.jpg",
    contain: true,
  },
]
